osx_image: xcode8
language: objective-c

before_install:
- brew update
- if brew outdated | grep -qx carthage; then brew upgrade carthage; fi
- travis_wait 35 carthage bootstrap --platform iOS,Mac

script:
- xcodebuild clean build -project Gallery.xcodeproj -scheme Gallery-iOS -sdk iphonesimulator
- xcodebuild test -project Gallery.xcodeproj -scheme Gallery-iOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0'
